# Generated by Django 3.0.dev20190812073926 on 2020-01-22 12:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nblog1', '0002_auto_20200122_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文本'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文本'),
        ),
    ]
