# Generated by Django 3.0.dev20190812073926 on 2020-01-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog1', '0003_auto_20200122_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, help_text='834829341@qq.com', max_length=254, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(verbose_name='回复内容'),
        ),
    ]
